ruby/deprecated/voqa/config/routes.rb
Rails.application.routes.draw do

  get 'questions/asked-by-me' => 'questions#asked_by_me'
  get 'questions/answered-by-me' => 'questions#answered_by_me'

  get 'questions/search' => 'questions#search'

  get 'about/' => 'about#index'

  devise_for :users

  resources :tags
  resources :votes
  resources :answers
  resources :questions

  root 'welcome#index'

end

ruby/deprecated/voqa/app/views/shared/_answers.html.erb
  <div id="answers_div">
    <h3>Answers (<%= @answers.count %>)</h3>
      <button id="answer_button" class="btn btn-default btn-lg" type="button" data-toggle="collapse" data-target="#answer_form" aria-expanded="false" aria-controls="answer_form">
        Post an Answer
      </button>


    <div class="collapse" id="answer_form" class="col-xs-6">
      <%= form_for(@answer, remote: true) do |f| %>
        <fieldset>
          <% if @answer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

              <ul>
              <% @answer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group col-xs-12">
            <%= f.text_area :content, autocomplete: "off", class: "form-control", placeholder: "content" %>
            <%= f.hidden_field :question_id, value: @question.id %>
          </div>

          <div class="form-group col-xs-12">
            <button id="cancel_answer" class="btn btn-danger btn-sm">Cancel</button>
            <%= f.submit "Post", id: "answer_submit",
                  class: "btn btn-primary btn-sm", data: { disable_with: "wait..." } %>
          </div>
        </fieldset>
      <% end %>
    </div>

    <table id="table" class="table table-hover">
    <tbody>
      <% @answers.each do |answer| %>
        <tr>
          <td data-title='answer' style="vertical-align: middle;">

            <div class="">
              <div id="up_vote_div-<%= answer.id %>" class="vote_div">
                <%= render(partial: 'shared/vote', locals: { answer: answer, vote_value: 1 }) %>
              </div>

              <div id="vote_value-<%= answer.id %>" style="font-size:1em; width: 1em;" class="text-center">
                <%= answer.votes.sum(:value) %>
              </div>
              
              <div id="down_vote_div-<%= answer.id %>" class="vote_div">
                <%= render(partial: 'shared/vote', locals: { answer: answer, vote_value: -1 }) %>
              </div>
            </div>
          </td>

          <td>
            <div class="col-sm-8">
              <p><%= answer.content %></p>
            </div>

            <div class="col-sm-2">
              <small>
                <figure>
                  <%= image_tag(gravatar_for(answer.user.email) + "?s=30", class: "img-circle small_circle", options: { alt: "#{answer.user.email} Gravatar" }) %>
                  <figcaption><strong><%= answer.user.username %></strong></figcaption>
                </figure>
              </small>
            </div>

            <div class="col-sm-2">
              <small>
                Answered <%= time_ago_in_words(answer.created_at) %> ago
                <br />
                Number of votes: <span id="vote_count-<%= answer.id %>"><%= answer.votes.count %></span>
              </small>
            </div>

          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  

ruby/deprecated/voqa/app/views/shared/_footer.html.erb
<footer>
  <nav>
    <% if !user_signed_in? %>
      <a href="#">Sign Up!</a>
    <% end %>
    <%= link_to "About Us", about_path %>
    <a href="#">Contact</a>
  </nav>

  <aside>&copy; 2015 VOresQ, LLC</aside>
</footer>

  

ruby/deprecated/voqa/app/views/shared/_logo.html.erb
<% welcome_style = params[:controller] == 'welcome' ? "height:200px" : "" %>

<div id="logo-container" class="navbar navbar-default navbar-fixed-top<%= non_welcome_col_settings %>">
  <%= link_to image_tag("voqa.svg", id: "voqa-logo", alt: "VOQA logo", class: "image-responsive center-block col-xs-12", style: "#{welcome_style}"), root_path %>
</div>

ruby/deprecated/voqa/app/views/shared/_question.html.erb
<div>
  <div class="col-sm-8">
    <span class='h4'><%= question.title %></span>
    <p><%= truncate(question.content, length: 80) %></p>
  </div>

  <div class="col-sm-2">
    <small class=''>
      Asked <%= time_ago_in_words(question.created_at) %> ago
      <br /> 
      <%= @answers.where(question_id: question.id).count %> Answers
    </small>
  </div>

  <div class="col-sm-2">
    <small class=''>
      <figure>
        <%= image_tag(gravatar_for(question.user.email) + "?s=50", class: "img-circle small_circle", options: { alt: "#{question.user.email} Gravatar" }) %>
        <figcaption><strong><%= question.user.username %></strong></figcaption>
      </figure>
    </small>
  </div>

</div>

ruby/deprecated/voqa/app/views/shared/_question_rows.html.erb
    <% @questions.each do |question| %>
      <tr>
        <td data-title='question'>
          <%= link_to render(partial: 'shared/question', locals: { question: question }), question_path(question) %>
        </td>
      </tr>
    <% end %>

ruby/deprecated/voqa/app/views/shared/_questions.html.erb
<div id="questions_div">

  <table id="table" class="table table-hover">
    <tbody>
      <%= render 'shared/question_rows' %>
    </tbody>
  </table>
  <% if @questions.count > 0 %>
    <%= will_paginate @questions %>
  <% end %>

</div>

ruby/deprecated/voqa/app/views/shared/_sidebar.html.erb
<nav id="sidebar" class="col-xs-4 col-sm-3 navbar">
  <div id="grav_name">
    <%= image_tag(gravatar_for(current_user[:email]), class: "img-circle", options: { alt: "#{current_user[:email]} Gravatar" }) %>
    <h1><%= current_user[:username] %></h1>
  </div>

  <div id="search" class="well">
    <%= form_tag(questions_search_path, method: 'get', class: 'form-inline center-block', role: 'form') do %>
      <fieldset>
          <div class="form-group">
            <%= text_field_tag :q, params[:q], autocomplete: "off", class: "form-control input-sm", placeholder: "search" %>
          </div>
          <div class="form-group">
            <%= link_to "clear", questions_path, class: "btn btn-default btn-sm" %>
            <%= submit_tag 'submit', id: "search_submit",
                class: "btn btn-success btn-sm", data: { disable_with: "wait..." } %>
          </div>
    <% end %>
  </div>

  <hr />

  <ul class="nav nav-stacked">
    <li role="presentation" class="h4">
      <button id="ask_button" class="btn btn-default btn-lg" type="button" data-toggle="collapse" data-target="#question_form" aria-expanded="false" aria-controls="question_form">
        Ask
      </button>
    </li>
  </ul>
  <div class="collapse text-left" id="question_form">
    <%= form_for(@question_new, remote: true) do |f| %>
      <fieldset>
        <legend>Ask a question!</legend>
        <% if @question_new.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@question_new.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
            <% @question_new.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group col-xs-12">
          <%= f.text_field :title, autocomplete: "off", class: "form-control", placeholder: "title" %>
        </div>

        <div class="form-group col-xs-12">
          <%= f.text_area :content, autocomplete: "off", class: "form-control", placeholder: "content" %>
        </div>

        <div class="form-group col-xs-12">
          <button id="cancel" class="btn btn-danger btn-sm">Cancel</button>
          <%= f.submit "Ask!", id: "ask_submit",
                class: "btn btn-primary btn-sm", data: { disable_with: "wait..." } %>
        </div>
      </fieldset>
    <% end %>
  </div>

  <hr />

  <!-- thank you http://glyphicons.com/ -->
  <ul class="nav nav-stacked">
    <li role="presentation" class="h4">
      <%= link_to(questions_asked_by_me_path, html_options = { class: 'qa_link' }) do %>
        <span class="qa">My Questions</span>
        <span id="q_count" class="qa_count label label-primary pull-right">
          <%= current_user_question_count %>
        </span>
      <% end %>
    </li>
    <li role="presentation" class="h4">
      <%= link_to(questions_answered_by_me_path, html_options = { class: 'qa_link' }) do %>
        <span class="qa">My Answers</span>
        <span id="a_count" class="qa_count label label-primary pull-right">
          <%= current_user_answer_count %>
        </span>
      <% end %>
    </li>
  </ul>

  <hr />

  <ul class="nav nav-stacked">
    <li role="presentation">
      <%= link_to "Account", edit_user_registration_path %>
    </li>
    <li role="presentation">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    </li>
  </ul>

  <hr />

  <ul class="nav nav-stacked">
    <li role="presentation">
      <a href="#">Contact Us</a>
    </li>
    <li role="presentation">
      <%= link_to "About Us", about_path %>
    </li>
  </ul>

</nav>

ruby/deprecated/voqa/app/views/shared/_vote.html.erb
<% # get string value %>
<% vote_type = vote_value == 1 ? "up" : "down" %>

<% # don't let current users vote on their answers %>
<% if answer.user_id == current_user.id %>

    <svg version="1.1"
         baseProfile="full"
         width="15" height="15"
         xmlns="http://www.w3.org/2000/svg" class="<%= vote_type %>_vote_disabled">
      <% if vote_type == "up" %>
        <polygon points='7.5,0 0,15 15,15' />
        UP
      <% elsif vote_type == "down" %>
        <polygon points='7.5,15 0,0 15,0' />
        DOWN
      <% end %>
    </svg>

<% else %>

  <% # check if other vote value is active for current user %>
  <% other_vote_active = Vote.where(value: (vote_value * -1), answer_id: answer.id, user_id: current_user.id) %>

  <% # check if this vote value is active for current user %>
  <% this_vote_active = Vote.where(value: vote_value, answer_id: answer.id, user_id: current_user.id) %>

  <% # if neither is active, it's a post %>
  <% if other_vote_active.empty? && this_vote_active.empty? %>

    <%= form_for @vote, 
        html: { class: "#{vote_type}_vote_form" }, 
        remote: true do |f| %>
      <%= f.hidden_field :value, value: vote_value %>
      <%= f.hidden_field :answer_id, value: answer.id %>
      <%= button_tag(class: "vote_button", data: { disable_with: "x" }) do %>
        <svg version="1.1"
             baseProfile="full"
             width="15" height="15"
             xmlns="http://www.w3.org/2000/svg" class="<%= vote_type %>_vote">
          <% if vote_type == "up" %>
            <polygon points='7.5,0 0,15 15,15' />
            UP
          <% elsif vote_type == "down" %>
            <polygon points='7.5,15 0,0 15,0' />
            DOWN
          <% end %>
        </svg>
      <% end %>
    <% end %>

  <% # if the other vote is active, it's a patch %>
  <% elsif other_vote_active.present? %>

    <%= form_for @vote, url: vote_path(other_vote_active.first.id), 
        method: :patch,
        html: { class: "#{vote_type}_vote_form" }, 
        remote: true do |f| %>
      <%= f.hidden_field :value, value: vote_value %>
      <%= f.hidden_field :answer_id, value: answer.id %>
      <%= button_tag(class: "vote_button", data: { disable_with: "x" }) do %>
        <svg version="1.1"
             baseProfile="full"
             width="15" height="15"
             xmlns="http://www.w3.org/2000/svg" class="<%= vote_type %>_vote">
          <% if vote_type == "up" %>
            <polygon points='7.5,0 0,15 15,15' />
            UP
          <% elsif vote_type == "down" %>
            <polygon points='7.5,15 0,0 15,0' />
            DOWN
          <% end %>
        </svg>
      <% end %>
    <% end %>

  <% # if the this vote is active, just show the svg %>
  <% elsif this_vote_active.present? %>

    <svg version="1.1"
         baseProfile="full"
         width="15" height="15"
         xmlns="http://www.w3.org/2000/svg" class="<%= vote_type %>_vote_active">
      <% if vote_type == "up" %>
        <polygon points='7.5,0 0,15 15,15' />
        UP
      <% elsif vote_type == "down" %>
        <polygon points='7.5,15 0,0 15,0' />
        DOWN
      <% end %>
    </svg>

  <% end %>

<% end %>