ruby/deprecated/voqa/config/routes.rb
Rails.application.routes.draw do

  get 'questions/asked-by-me' => 'questions#asked_by_me'
  get 'questions/answered-by-me' => 'questions#answered_by_me'

  get 'questions/search' => 'questions#search'

  get 'about/' => 'about#index'

  devise_for :users

  resources :tags
  resources :votes
  resources :answers
  resources :questions

  root 'welcome#index'

end

ruby/deprecated/voqa/app/models/vote.rb
class Vote < ActiveRecord::Base

  include ValidationHelpers
  before_validation :answerer_is_not_voter?

  belongs_to :user
  belongs_to :answer

  validates :value, :answer_id, :user_id, presence: true, if: [:user_id_is_valid?, :answer_id_is_valid?]
  #validates :value, numericality: { only_integer: true }
  validates :value, inclusion: { in: [-1, 1] }
  validates_uniqueness_of :answer_id, { scope: :user_id }

end

ruby/deprecated/voqa/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  #before_action :set_vote, only: [:show, :edit, :update, :destroy]
  before_action :set_vote, only: [:show, :update]

  # GET /votes
  # GET /votes.json
  def index
    #@votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    #@vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        #format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        #format.json { render :show, status: :created, location: @vote }
        format.js { 
          @votes = Vote.where(answer_id: @vote.answer_id)
          @value = @votes.sum(:value)

          @question = Question.find(Answer.find(@vote.answer_id).question_id)

          @answer = Answer.new
          @answers = Answer.includes(:user,:votes).where(question_id: @question.id).order(:created_at)
          @answers = @answers.sort {|a,b| b.votes.sum(:value) <=> a.votes.sum(:value)}
        }
      else
        #format.html { render :new }
        #format.json { render json: @vote.errors, status: :unprocessable_entity }
        format.js { @vote.errors }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        #format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        #format.json { render :show, status: :ok, location: @vote }
        format.js { 
          @votes = Vote.where(answer_id: @vote.answer_id)
          @value = @votes.sum(:value)

          @question = Question.find(Answer.find(@vote.answer_id).question_id)

          @answer = Answer.new
          @answers = Answer.includes(:user,:votes).where(question_id: @question.id).order(:created_at)
          @answers = @answers.sort {|a,b| b.votes.sum(:value) <=> a.votes.sum(:value)}
        }
      else
        #format.html { render :edit }
        #format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:value, :answer_id).merge(user_id: current_user.id)
    end
end

ruby/deprecated/voqa/app/views/votes/old/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/deprecated/voqa/app/views/votes/old/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

ruby/deprecated/voqa/app/views/votes/old/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.value %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

ruby/deprecated/voqa/app/views/votes/old/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

ruby/deprecated/voqa/app/views/votes/old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @vote.value %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>